package org.crazyit.gongyi.module;

// Generated 2013-11-24 15:02:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Set;

/**
 * GyAds generated by hbm2java
 */
public class GyAds implements java.io.Serializable {

	private Long adId;
	private GyCompany adCompany;
	private String adName;
	private String adDesc;
	private String adUrl;
	private double maxAmount;
	private double minAmount;
	private double useAmount;
	private Date doneDate;
	private int recStatus;
	private String notes;
	private Set<GySeeker> adSeekers;

	public GyAds() {
	}

	public Long getAdId() {
		return this.adId;
	}

	public void setAdId(Long adId) {
		this.adId = adId;
	}

	public GyCompany getAdCompany() {
		return this.adCompany;
	}

	public void setAdCompany(GyCompany adCompany) {
		this.adCompany = adCompany;
	}

	public String getAdName() {
		return this.adName;
	}

	public void setAdName(String adName) {
		this.adName = adName;
	}

	public String getAdDesc() {
		return this.adDesc;
	}

	public void setAdDesc(String adDesc) {
		this.adDesc = adDesc;
	}

	public String getAdUrl() {
		return this.adUrl;
	}

	public void setAdUrl(String adUrl) {
		this.adUrl = adUrl;
	}

	public double getMaxAmount() {
		return this.maxAmount;
	}

	public void setMaxAmount(double maxAmount) {
		this.maxAmount = maxAmount;
	}

	public double getMinAmount() {
		return this.minAmount;
	}

	public void setMinAmount(double minAmount) {
		this.minAmount = minAmount;
	}

	public double getUseAmount() {
		return this.useAmount;
	}

	public void setUseAmount(double useAmount) {
		this.useAmount = useAmount;
	}

	public Date getDoneDate() {
		return this.doneDate;
	}

	public void setDoneDate(Date doneDate) {
		this.doneDate = doneDate;
	}

	public int getRecStatus() {
		return this.recStatus;
	}

	public void setRecStatus(int recStatus) {
		this.recStatus = recStatus;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public Set<GySeeker> getAdSeekers() {
		return adSeekers;
	}

	public void setAdSeekers(Set<GySeeker> adSeekers) {
		this.adSeekers = adSeekers;
	}

}
