package org.crazyit.gongyi.module;

// Generated 2013-11-24 15:02:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Set;

/**
 * GyCompany generated by hbm2java
 */
public class GyCompany implements java.io.Serializable {

	private Long companyId;
	private int companyType;
	private String companyName;
	private String companyAddr;
	private Date doneDate;
	private int recStatus;
	private String notes;
	private Set<GyAds> ads;

	

	public Set<GyAds> getAds() {
		return ads;
	}

	public void setAds(Set<GyAds> ads) {
		this.ads = ads;
	}

	public GyCompany() {
	}

	public GyCompany(int companyType, String companyName, Date doneDate,
			int recStatus) {
		this.companyType = companyType;
		this.companyName = companyName;
		this.doneDate = doneDate;
		this.recStatus = recStatus;
	}

	public GyCompany(int companyType, String companyName, String companyAddr,
			Date doneDate, int recStatus, String notes) {
		this.companyType = companyType;
		this.companyName = companyName;
		this.companyAddr = companyAddr;
		this.doneDate = doneDate;
		this.recStatus = recStatus;
		this.notes = notes;
	}

	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public int getCompanyType() {
		return this.companyType;
	}

	public void setCompanyType(int companyType) {
		this.companyType = companyType;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getCompanyAddr() {
		return this.companyAddr;
	}

	public void setCompanyAddr(String companyAddr) {
		this.companyAddr = companyAddr;
	}

	public Date getDoneDate() {
		return this.doneDate;
	}

	public void setDoneDate(Date doneDate) {
		this.doneDate = doneDate;
	}

	public int getRecStatus() {
		return this.recStatus;
	}

	public void setRecStatus(int recStatus) {
		this.recStatus = recStatus;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
