package org.crazyit.gongyi.module;

// Generated 2013-11-24 15:02:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * GyDonation generated by hbm2java
 */
public class GyDonation implements java.io.Serializable {

	private long id;
	private int helpType;
	private Double helpAmount;
	private Date doneDate;
	private int recStatus;
	private String notes;
	private GyUser donateUser;
	private GySeeker donateSeeker;
	private GyAds donateAd;

	public GyDonation() {
	}

	public GyUser getDonateUser() {
		return donateUser;
	}

	public void setDonateUser(GyUser donateUser) {
		this.donateUser = donateUser;
	}

	public GySeeker getDonateSeeker() {
		return donateSeeker;
	}

	public void setDonateSeeker(GySeeker donateSeeker) {
		this.donateSeeker = donateSeeker;
	}

	public GyAds getDonateAd() {
		return donateAd;
	}

	public void setDonateAd(GyAds donateAd) {
		this.donateAd = donateAd;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public int getHelpType() {
		return this.helpType;
	}

	public void setHelpType(int helpType) {
		this.helpType = helpType;
	}

	public Double getHelpAmount() {
		return this.helpAmount;
	}

	public void setHelpAmount(Double helpAmount) {
		this.helpAmount = helpAmount;
	}

	public Date getDoneDate() {
		return this.doneDate;
	}

	public void setDoneDate(Date doneDate) {
		this.doneDate = doneDate;
	}

	public int getRecStatus() {
		return this.recStatus;
	}

	public void setRecStatus(int recStatus) {
		this.recStatus = recStatus;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
