package org.crazyit.gongyi.module;

// Generated 2013-11-24 15:02:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Set;

/**
 * GyProv generated by hbm2java
 */
public class GyProv implements java.io.Serializable {

	private Long id;
	private int provId;
	private String provName;
	private Date doneDate;
	private int recStatus;
	private String notes;
	private Set<GyUser> provUsers;
	private Set<GySeeker> provSeekers;
	private Set<GyZone> provZones;

	public Set<GyZone> getProvZones() {
		return provZones;
	}

	public void setProvZones(Set<GyZone> provZones) {
		this.provZones = provZones;
	}

	public Set<GyUser> getProvUsers() {
		return provUsers;
	}

	public void setProvUsers(Set<GyUser> provUsers) {
		this.provUsers = provUsers;
	}

	public Set<GySeeker> getProvSeekers() {
		return provSeekers;
	}

	public void setProvSeekers(Set<GySeeker> provSeekers) {
		this.provSeekers = provSeekers;
	}

	public GyProv() {
	}

	public GyProv(int provId, String provName, Date doneDate, int recStatus) {
		this.provId = provId;
		this.provName = provName;
		this.doneDate = doneDate;
		this.recStatus = recStatus;
	}

	public GyProv(int provId, String provName, Date doneDate, int recStatus,
			String notes) {
		this.provId = provId;
		this.provName = provName;
		this.doneDate = doneDate;
		this.recStatus = recStatus;
		this.notes = notes;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public int getProvId() {
		return this.provId;
	}

	public void setProvId(int provId) {
		this.provId = provId;
	}

	public String getProvName() {
		return this.provName;
	}

	public void setProvName(String provName) {
		this.provName = provName;
	}

	public Date getDoneDate() {
		return this.doneDate;
	}

	public void setDoneDate(Date doneDate) {
		this.doneDate = doneDate;
	}

	public int getRecStatus() {
		return this.recStatus;
	}

	public void setRecStatus(int recStatus) {
		this.recStatus = recStatus;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
