package org.crazyit.gongyi.module;

// Generated 2013-11-24 15:02:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Set;

/**
 * GySeeker generated by hbm2java
 */
public class GySeeker implements java.io.Serializable {

	private Long seekerId;
	private String seekerName;
	private String seekerAddr;
	private String title;
	private String seekerDesc;
	private double needAmount;
	private Double helpAmount;
	private Integer helpCount;
	private Integer browseCount;
	private Date createDate;
	private Date doneDate;
	private int recStatus;
	private String notes;
	private GyProv seekerProv;
	private GyZone seekerZone;
	private GyAds seekerAd;
	private String photo;
	private Set<GyUser> seekerUsers;

	public GySeeker() {
	}

	public Long getSeekerId() {
		return this.seekerId;
	}

	public void setSeekerId(Long seekerId) {
		this.seekerId = seekerId;
	}

	public String getSeekerName() {
		return this.seekerName;
	}

	public void setSeekerName(String seekerName) {
		this.seekerName = seekerName;
	}

	public String getSeekerAddr() {
		return this.seekerAddr;
	}

	public void setSeekerAddr(String seekerAddr) {
		this.seekerAddr = seekerAddr;
	}

	public String getSeekerDesc() {
		return this.seekerDesc;
	}

	public void setSeekerDesc(String seekerDesc) {
		this.seekerDesc = seekerDesc;
	}

	public double getNeedAmount() {
		return this.needAmount;
	}

	public void setNeedAmount(double needAmount) {
		this.needAmount = needAmount;
	}

	public Double getHelpAmount() {
		return this.helpAmount;
	}

	public void setHelpAmount(Double helpAmount) {
		this.helpAmount = helpAmount;
	}

	public Integer getHelpCount() {
		return this.helpCount;
	}

	public void setHelpCount(Integer helpCount) {
		this.helpCount = helpCount;
	}

	public Integer getBrowseCount() {
		return this.browseCount;
	}

	public void setBrowseCount(Integer browseCount) {
		this.browseCount = browseCount;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getDoneDate() {
		return this.doneDate;
	}

	public void setDoneDate(Date doneDate) {
		this.doneDate = doneDate;
	}

	public int getRecStatus() {
		return this.recStatus;
	}

	public void setRecStatus(int recStatus) {
		this.recStatus = recStatus;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public GyProv getSeekerProv() {
		return seekerProv;
	}

	public void setSeekerProv(GyProv seekerProv) {
		this.seekerProv = seekerProv;
	}

	public GyZone getSeekerZone() {
		return seekerZone;
	}

	public void setSeekerZone(GyZone seekerZone) {
		this.seekerZone = seekerZone;
	}

	public GyAds getSeekerAd() {
		return seekerAd;
	}

	public void setSeekerAd(GyAds seekerAd) {
		this.seekerAd = seekerAd;
	}

	public Set<GyUser> getSeekerUsers() {
		return seekerUsers;
	}

	public void setSeekerUsers(Set<GyUser> seekerUsers) {
		this.seekerUsers = seekerUsers;
	}

	public String getPhoto() {
		return photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
	
}
