package org.crazyit.gongyi.module;

// Generated 2013-11-24 15:02:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Set;

/**
 * GyUser generated by hbm2java
 */
public class GyUser implements java.io.Serializable {

	private Long userId;
	private int userType;
	private String userAcct;
	private String userName;
	private String password;
	private Integer ageType;
	private Integer gender;
	private Date createDate;
	private Date doneDate;
	private int recStatus;
	private String notes;
	private GyProv userProv;
	private GyZone userZone;
	private Set<GySeeker> userSeekers;

	public GyUser() {
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public int getUserType() {
		return this.userType;
	}

	public void setUserType(int userType) {
		this.userType = userType;
	}

	public String getUserAcct() {
		return this.userAcct;
	}

	public void setUserAcct(String userAcct) {
		this.userAcct = userAcct;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getAgeType() {
		return this.ageType;
	}

	public void setAgeType(Integer ageType) {
		this.ageType = ageType;
	}

	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	public GyProv getUserProv() {
		return userProv;
	}

	public void setUserProv(GyProv userProv) {
		this.userProv = userProv;
	}

	public GyZone getUserZone() {
		return userZone;
	}

	public void setUserZone(GyZone userZone) {
		this.userZone = userZone;
	}

	public Set<GySeeker> getUserSeekers() {
		return userSeekers;
	}

	public void setUserSeekers(Set<GySeeker> userSeekers) {
		this.userSeekers = userSeekers;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getDoneDate() {
		return this.doneDate;
	}

	public void setDoneDate(Date doneDate) {
		this.doneDate = doneDate;
	}

	public int getRecStatus() {
		return this.recStatus;
	}

	public void setRecStatus(int recStatus) {
		this.recStatus = recStatus;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
