package org.crazyit.gongyi.module;

// Generated 2013-11-24 15:02:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Set;

/**
 * GyZone generated by hbm2java
 */
public class GyZone implements java.io.Serializable {

	private Long id;
	private int zoneId;
	private String zoneName;
	private Date doneDate;
	private int recStatus;
	private String notes;
	private GyProv zoneProv;
	private Set<GyUser> zoneUsers;
	private Set<GySeeker> zoneSeekers;

	public GyZone() {
	}

	public GyProv getZoneProv() {
		return zoneProv;
	}

	public void setZoneProv(GyProv zoneProv) {
		this.zoneProv = zoneProv;
	}

	public Set<GyUser> getZoneUsers() {
		return zoneUsers;
	}

	public void setZoneUsers(Set<GyUser> zoneUsers) {
		this.zoneUsers = zoneUsers;
	}

	public Set<GySeeker> getZoneSeekers() {
		return zoneSeekers;
	}

	public void setZoneSeekers(Set<GySeeker> zoneSeekers) {
		this.zoneSeekers = zoneSeekers;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public int getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(int zoneId) {
		this.zoneId = zoneId;
	}

	public String getZoneName() {
		return this.zoneName;
	}

	public void setZoneName(String zoneName) {
		this.zoneName = zoneName;
	}

	public Date getDoneDate() {
		return this.doneDate;
	}

	public void setDoneDate(Date doneDate) {
		this.doneDate = doneDate;
	}

	public int getRecStatus() {
		return this.recStatus;
	}

	public void setRecStatus(int recStatus) {
		this.recStatus = recStatus;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
